# Generated by Django 5.2.4 on 2025-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_courses'),
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.course'),
        ),
    ]
