# Generated by Django 5.2.4 on 2025-07-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklistedaccesstoken'),
        ('courses', '0004_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
