# Generated by Django 5.2.4 on 2025-07-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseenrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
    ]
