# Generated by Django 5.2.4 on 2025-08-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
    ]
